// <auto-generated />
using System;
using GrowKitApi.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace GrowKitApi.Migrations.Application
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190628144359_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("GrowKitApi.Entities.ApplicationUser", b =>
                {
                    b.Property<long>("UserId");

                    b.Property<string>("NormalizedUsername");

                    b.Property<string>("Username");

                    b.HasKey("UserId");

                    b.ToTable("ApplicationUsers");
                });

            modelBuilder.Entity("GrowKitApi.Entities.AuthenticationUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("AuthenticatorSecret");

                    b.Property<short>("Flags");

                    b.Property<string>("NormalizedEmailAdress");

                    b.Property<byte[]>("PasswordHash");

                    b.Property<byte[]>("PasswordSalt");

                    b.Property<long>("PreviousTimeWindow");

                    b.HasKey("Id");

                    b.ToTable("AuthenticationUser");
                });

            modelBuilder.Entity("GrowKitApi.Entities.GrowKitStick", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ActivePresetId");

                    b.Property<int>("Light");

                    b.Property<int>("LightTime");

                    b.Property<long>("MasterStickId");

                    b.Property<int>("Moisture");

                    b.Property<long>("OwnerId");

                    b.Property<int>("Temperature");

                    b.Property<int>("TimestampUpdate");

                    b.HasKey("Id");

                    b.HasIndex("ActivePresetId");

                    b.HasIndex("MasterStickId");

                    b.HasIndex("OwnerId");

                    b.ToTable("SensorSticks");
                });

            modelBuilder.Entity("GrowKitApi.Entities.PlantPreset", b =>
                {
                    b.Property<int>("PresetId")
                        .ValueGeneratedOnAdd();

                    b.Property<int[]>("Light");

                    b.Property<int[]>("Moisture");

                    b.Property<int[]>("Sunshine");

                    b.Property<int[]>("Temperature");

                    b.HasKey("PresetId");

                    b.ToTable("PlantPresets");
                });

            modelBuilder.Entity("GrowKitApi.Entities.ApplicationUser", b =>
                {
                    b.HasOne("GrowKitApi.Entities.AuthenticationUser", "AuthenticationUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GrowKitApi.Entities.GrowKitStick", b =>
                {
                    b.HasOne("GrowKitApi.Entities.PlantPreset", "ActivePreset")
                        .WithMany()
                        .HasForeignKey("ActivePresetId");

                    b.HasOne("GrowKitApi.Entities.GrowKitStick", "MasterStick")
                        .WithMany()
                        .HasForeignKey("MasterStickId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GrowKitApi.Entities.ApplicationUser", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
